### ISSUE TITLE
Scraping images as text problem

### ISSUE THREAD

**Issue by Anonyfox** [Anonyfox/meteor-scrape#4]
This kills the CPU. Scrape must detect if the requested data is binary or text, and stop parsing if it is binary.

**Comment by rashinari** [comment]
Included MIME Type Detection in modul ScrapeRequest to switch between different types of response (included HTML, TEXT, JSON, and all others as binary buffer)

**Comment by rashinari** [comment]
JSON Response types are auto converted to JavaScript Objects.
